# permissions for end users to view netdevs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netdevs-viewer-role
rules:
- apiGroups:
  - network.networkconfigoperator
  resources:
  - netdevs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.networkconfigoperator
  resources:
  - netdevs/status
  verbs:
  - get
