
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - network.networkconfigoperator
  resources:
  - netdevs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.networkconfigoperator
  resources:
  - netdevs/finalizers
  verbs:
  - update
- apiGroups:
  - network.networkconfigoperator
  resources:
  - netdevs/status
  verbs:
  - get
  - patch
  - update
