apiVersion: network.networkconfigoperator/v1
kind: NetDevs
metadata:
  name: ceos2
  namespace: networkconfig
spec:
  username: admin
  password: admin
  host: 192.168.4.244
  transport: http
  port: 889
  networkos: eos
  runningconfig:  |+
    transceiver qsfp default-mode 4x10G
    !
    service routing protocols model multi-agent
    !
    hostname ceos2
    !
    spanning-tree mode mstp
    !
    no aaa root
    !
    username admin privilege 15 role network-admin secret sha512 $6$S1jDtSEN/M3/VEsP$fNT4jByGEaYNlEnDxw4qCAyV3dsc/JH5Q7nLLStzZIo0TwUQ3aPuIO2sqVXalm8K74ccIeWQSanzAU5zT9Nj31
    !
    interface Ethernet1
      no switchport
      ip address 10.0.0.2/24
    !
    interface Loopback0
      ip address 2.2.2.2/32
    !
    interface Management0
      ip address 172.20.20.3/24
      ipv6 address 2001:172:20:20::2/64
    !
    ip access-list copp
      10 permit ip any any
    !
    ip routing
    !
    system control-plane
      ip access-group copp in
    !
    router bgp 65002
      neighbor 10.0.0.1 remote-as 65001
      redistribute connected
    !
    router ospf 1
      network 0.0.0.0/0 area 0.0.0.0
      max-lsa 12000
    !
    management api http-commands
      protocol http
      no shutdown
    !
    management api gnmi
      transport grpc default
    !
    management api netconf
      transport ssh default
    !
    end
